---
- hosts: myhosts
  connection: local
  name: Set default BIOS settings
  gather_facts: False

  tasks:

  - name: Set BIOS default settings
    redfish_config:
      category: Systems
      command: SetBiosDefaultSettings
      baseuri: "{{ baseuri }}"
      user: "{{ username }}"
      password: "{{ password }}"
    register: bios_default

  - name: Reboot system to apply new BIOS settings
    redfish_command:
      category: Systems
      command: PowerGracefulRestart
      baseuri: "{{ baseuri }}"
      user: "{{ username }}"
      password: "{{ password }}"
    when: bios_default.changed
