---
- hosts: myhosts
  name: PowerEdge iDRAC
  gather_facts: False

  # Here we define global variables, but if some servers have different
  # credentials, then place these variables in /etc/ansible/hosts to override
  # for each host
  vars:
     rootdir: /root			# where I place all results 
     idracuser: root
     idracpswd: calvin
     sharehost: 10.9.165.171
     sharename: share2
     shareuser: dell
     sharepswd: 111111

  # Data available:
  #   Health		Get server health
  #   Model		Get server model
  #   BiosVersion	Get BIOS version
  #   AssetTag		Get asset tag
  #   Memory		Get system memory (GB)
  #   CPU		Get CPU model
  #   ConsumedWatts	Get power consumed (watts)
  #   Selog		Get SELogs
  #   PowerState	Get power state (On/Off)
  #   PowerOn		Power on system (coming soon)
  #   PowerOff		Power off system (coming soon)
  #   SCP		Export Server Configuration Profile (SCP)

  tasks:

  - name: Set timestamp variable
    set_fact: timestamp="{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"

  - name: Create dropoff dir for host if needed
    local_action: file path={{rootdir}}/{{host}} state=directory

  - name: Get information
    include: get_info.yml action={{item}}
             outfile={{rootdir}}/{{host}}/{{host}}_info_{{timestamp}}
    with_items:
      - Health
      - Model
      - BiosVersion
      - AssetTag
      - Memory
      - CPU
      - ConsumedWatts
      - PowerState
      - PowerRestart

  - name: Get SELogs
    include: get_info.yml action=Selog
             outfile={{rootdir}}/{{host}}/{{host}}_SELogs_{{timestamp}}.json

  - name: Export SCP file
    local_action: >
       idrac choice=SCP idracuser={{ idracuser }} idracpswd={{ idracpswd }}
       idracip={{ idracip }} sharehost={{ sharehost }} sharename={{ sharename }}
       shareuser={{ shareuser }} sharepswd={{ sharepswd }} hostname={{ host }}

