---
- hosts: myhosts
  connection: local
  name: Add User
  gather_facts: False

  tasks:

  # When adding a user, it must be enabled afterwards
  - name: Add user
    redfish_command:
      category: Accounts
      command: AddUser
      baseuri: "{{ baseuri }}"
      user: "{{ username }}"
      password: "{{ password }}"
      userid: "{{ id }}"
      username: "{{ new_username }}"
      userpswd: "{{ new_password }}"
      userrole: "{{ roleid }}"
