---
- hosts: myhosts
  connection: local
  name: Disable User
  gather_facts: False

  tasks:

  - name: Disable user
    redfish_command:
      category: Accounts
      command: DisableUser
      baseuri: "{{ baseuri }}"
      user: "{{ username }}"
      password: "{{ password }}"
      userid: "{{ id }}"
