---
- hosts: myhosts
  connection: local
  name: Update user password
  gather_facts: False

  tasks:

  - name: Update user password
    redfish_command:
      category: Accounts
      command: UpdateUserPassword
      baseuri: "{{ baseuri }}"
      user: "{{ username }}"
      password: "{{ password }}"
      userid: "{{ id }}"
      userpswd: "{{ new_password }}"
