---
- hosts: myhosts
  connection: local
  name: Update user role
  gather_facts: False

  tasks:

  - name: Update user role
    redfish_command:
      category: Accounts
      command: UpdateUserRole
      baseuri: "{{ baseuri }}"
      user: "{{ username }}"
      password: "{{ password }}"
      userid: "{{ id }}"
      userrole: "{{ roleid }}"
