---
- hosts: myhosts
  name: PowerEdge Firmware Update 
  gather_facts: False
  vars:
      idracuser: root
      idracpswd: calvin

  tasks:

  - name: upload firmware image
    local_action: >
        idrac category=Firmware command=UploadFirmware idracip={{idracip}} FWPath=/root/iDRAC-with-Lifecycle-Controller_Firmware_GMN0H_WN64_3.02.00.01_A00.EXE
        idracuser={{idracuser}} idracpswd={{idracpswd}}
    register: FWResult
    ignore_errors: yes



